AllCops:
  Exclude:
    - 'storage/**/*'
    - 'Rakefile'
    - 'Gemfile'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/*'
Metrics/ClassLength:
  Max: 1500

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'register', 'shared_examples_for']

Style/Lambda:
  EnforcedStyle: literal

Naming/VariableNumber:
  EnforcedStyle: snake_case